stages:
 - deplopy_CB_FW
 - environment_test
 - smoke_test
 - full_tests


core_FW_Update_and_FactoryReset: 
  stage: deplopy_CB_FW
  tags:
   - shell
   - linux
   
  image: python:3.7
  variables:
   WP_HOST_IP: 172.23.31.53
   WP_HOST_PASSWORD: Password
   WP_JSON_FILE: ../wolfprot.json
   WP_HOST_MAC: 04:92:26:4A:FB:62
   WP_HELPER_HOST_PASSWORD: Password
   
  script:
   - python3 wolfprot_module/wolfprot/cynap_tool.py -i $WP_HOST_IP -p $WP_HOST_PASSWORD -f ./wolfprot.json  -u /media/buildserver/firmware/cynap/nightly_develop/latest/cbc.wgz
   - python3 wolfprot_module/wolfprot/cynap_tool.py -i $WP_HOST_IP -p $WP_HOST_PASSWORD -f ./wolfprot.json -factory_reset
   - python3 wolfprot_module/wolfprot/cynap_tool.py -i $WP_HOST_IP -p $WP_HOST_PASSWORD -f ./wolfprot.json --change_boxname TW-Core-PyTests-Testing
      
  only: 
   - schedules
  artifacts:
    when: always
    reports:
      junit: report-*.xml


cynap_FW_Update_and_FactoryReset: 
  stage: deplopy_CB_FW
  tags:
   - shell
   - linux
   
  image: python:3.7
  variables:
   WP_HOST_IP: 172.23.31.57
   WP_HOST_PASSWORD: Password
   WP_JSON_FILE: ../wolfprot.json
   WP_HOST_MAC: 08:60:6E:F9:F8:48
   WP_HELPER_HOST_PASSWORD: Password
  before_script:
  script:
   - ssh-keygen -f "/home/gitlab-runner/.ssh/known_hosts" -R $WP_HOST_IP
   - python3 wolfprot_module/wolfprot/cynap_tool.py -i $WP_HOST_IP -p $WP_HOST_PASSWORD -f ./wolfprot.json  -u /media/buildserver/firmware/cynap/nightly_develop/latest/cb1.wgz
   - python3 wolfprot_module/wolfprot/cynap_tool.py -i $WP_HOST_IP -p $WP_HOST_PASSWORD -f ./wolfprot.json -factory_reset
   - python3 wolfprot_module/wolfprot/cynap_tool.py -i $WP_HOST_IP -p $WP_HOST_PASSWORD -f ./wolfprot.json --change_boxname TW-Cynap-PyTests-Testing
   
  only: 
   - schedules
  artifacts:
    when: always
    reports:
      junit: report-*.xml

PurePro_FW_Update_and_FactoryReset: 
  stage: deplopy_CB_FW
  tags:
   - shell
   - linux
   
  image: python:3.7
  variables:
   WP_HOST_IP: 172.23.31.50
   WP_HOST_PASSWORD: Password
   WP_JSON_FILE: ../wolfprot.json
  before_script:
  script:
   - ssh-keygen -f "/home/gitlab-runner/.ssh/known_hosts" -R $WP_HOST_IP
   - python3 wolfprot_module/wolfprot/cynap_tool.py -i $WP_HOST_IP -p $WP_HOST_PASSWORD -f ./wolfprot.json  -u /media/buildserver/firmware/cynap/nightly_develop/latest/cpp.wgz
   - python3 wolfprot_module/wolfprot/cynap_tool.py -i $WP_HOST_IP -p $WP_HOST_PASSWORD -f ./wolfprot.json -factory_reset
   - python3 wolfprot_module/wolfprot/cynap_tool.py -i $WP_HOST_IP -p $WP_HOST_PASSWORD -f ./wolfprot.json --change_boxname TW-PurePro-PyTests-Testing
   
  only: 
   - schedules
  artifacts:
    when: always
    reports:
      junit: report-*.xml


environment_test: 
  stage: environment_test
  tags:
   - shell
   - pytest
   - linux
  variables:
   WP_HOST_IP: 172.23.31.57
   WP_HOST_PASSWORD: Password
   WP_JSON_FILE: ../wolfprot.json
   WP_HOST_MAC: 08:60:6E:F9:F8:48
   WP_HELPER_HOST_IP: 172.23.31.53
   WP_HELPER_HOST_PASSWORD: Password
   K8S_SECRET_WP_SSH_PASSWORD: $WP_SSH_PASSWORD
  before_script:
   - python3 -m pip install -e wolfprot_module/
   - python3 -m pip install -r requirements.txt
   - python3 -m pip install pycryptodome
   - python3 -m pip install keyring
  script:
   - cd pytests
   - python3 -m pytest environment --junitxml=../report.xml 
    
  artifacts:
    when: always
    reports:
      junit: report.xml

cynap_full_test: 
  stage: full_tests
  tags:
   - shell
   - pytest
   - linux
   
  image: python:3.7
  variables:
   WP_HOST_IP: 172.23.31.57
   WP_HOST_PASSWORD: Password
   WP_JSON_FILE: ../wolfprot.json
   WP_HOST_MAC: 08:60:6E:F9:F8:48
   WP_HELPER_HOST_IP: 172.23.31.53
   WP_HELPER_HOST_PASSWORD: Password
   K8S_SECRET_WP_SSH_PASSWORD: $WP_SSH_PASSWORD
  before_script:
   - python3 -m pip install -e wolfprot_module/
   - python3 -m pip install -r requirements.txt
   - python3 -m pip install pycryptodome
   - python3 -m pip install keyring
   - apt update && apt install --no-install-recommends -y tesseract-ocr
  script:
   - cd pytests
   - python3 -m pytest general --junitxml=../report-general.xml -E CB_ASSOCIATE -E LINUX
   - python3 -m pytest network_drive --junitxml=../report-network_drive.xml
   - python3 -m pytest ftp --junitxml=../report-ftp.xml 
   - python3 -m pytest peripheral_control --junitxml=../report-peripheral_control.xml 
   - python3 -m pytest cloud --junitxml=../report-cloud.xml -E USB_STICK   
   - python3 -m pytest audio --junitxml=../report-audio.xml -E USB_STICK -E=LINE_IN -E=CB_ASSOCIATE
   - python3 -m pytest input --junitxml=../report-input.xml -E=CB_ASSOCIATE -E=HDMI_IN
   #- python3 -m pytest output --junitxml=../report-output.xml -E CB_ASSOCIATE -E LINUX
   - python3 -m pytest security --junitxml=../report-Security.xml     
   # Before uncommenting this test Wolfprot.json file has to be updated 
   #- python3 -m pytest recording_streaming/test_panopto_upload.py --junitxml=../report-recording_streaming.xml -E=IP_CAM
   - cd ..
   - python3 wolfprot_module/wolfprot/cynap_tool.py -i $WP_HOST_IP -p $WP_HOST_PASSWORD -f ./wolfprot.json --change_boxname TW-Cynap-PyTests-Free
   
  only: 
   - schedules
  artifacts:
    when: always
    reports:
      junit: report-*.xml

PurePro_full_test: 
  stage: full_tests
  tags:
   - shell
   - pytest
   - linux
   
  image: python:3.7
  variables:
   WP_HOST_IP: 172.23.31.50
   WP_HOST_PASSWORD: Password
   WP_JSON_FILE: ../wolfprot.json
   WP_HOST_MAC: 54:B2:03:89:54:95
   WP_HELPER_HOST_IP: 172.23.31.53
   WP_HELPER_HOST_PASSWORD: Password
   K8S_SECRET_WP_SSH_PASSWORD: $WP_SSH_PASSWORD
  before_script:
   - python3 -m pip install -e wolfprot_module/
   - python3 -m pip install -r requirements.txt
   - python3 -m pip install pycryptodome
   - python3 -m pip install keyring
   - apt update && apt install --no-install-recommends -y tesseract-ocr
  script:
   - cd pytests
   - python3 -m pytest general --junitxml=../report-general.xml -E CB_ASSOCIATE -E LINUX
   - python3 -m pytest -m CPP network_drive --junitxml=../report-network_drive.xml
   - python3 -m pytest ftp --junitxml=../report-ftp.xml 
   - python3 -m pytest peripheral_control --junitxml=../report-peripheral_control.xml 
   - python3 -m pytest cloud --junitxml=../report-Cloud.xml -E USB_STICK
   - python3 -m pytest security --junitxml=../report-security.xml
   #- python3 -m pytest output --junitxml=../report-output.xml -E CB_ASSOCIATE -E LINUX

   - cd ..
   - python3 wolfprot_module/wolfprot/cynap_tool.py -i $WP_HOST_IP -p $WP_HOST_PASSWORD -f ./wolfprot.json --change_boxname TW-PurePro-PyTests-Free
   # move this to the core_full_test as soon as they run stable
   - python3 wolfprot_module/wolfprot/cynap_tool.py -i 172.23.31.53 -p $WP_HOST_PASSWORD -f ./wolfprot.json --change_boxname TW-Core-PyTests-Free
   
  only: 
   - schedules
  artifacts:
    when: always
    reports:
      junit: report-*.xml


core_full_test: 
  stage: full_tests
  tags:
   - shell
   - pytest
   - linux
   
  image: python:3.7
  variables:
    WP_HOST_IP: 172.23.31.53
    WP_HOST_PASSWORD: Password
    WP_JSON_FILE: ../wolfprot.json
    WP_HOST_MAC: 04:92:26:4A:FB:62
    WP_HELPER_HOST_IP: 172.23.31.57
    WP_HELPER_HOST_PASSWORD: Password
    K8S_SECRET_WP_SSH_PASSWORD: $WP_SSH_PASSWORD
  before_script:
    - python3 -m pip install -e wolfprot_module/
    - python3 -m pip install -r requirements.txt
    - python3 -m pip install pycryptodome
    - python3 -m pip install keyring
  script:
    - cd pytests
    - python3 -m pytest general --junitxml=../report-general.xml -E CB_ASSOCIATE -E LINUX
    - python3 -m pytest network_drive --onlyCBC --junitxml=../report-network_drive.xml
    - python3 -m pytest ftp --junitxml=../report-ftp.xml 
    - python3 -m pytest peripheral_control --junitxml=../report-peripheral_control.xml 
    - python3 -m pytest cloud --junitxml=../report-cloud.xml -E USB_STICK
    - python3 -m pytest audio --junitxml=../report-audio.xml -E USB_STICK -E=LINE_IN -E=CB_ASSOCIATE    
    #- python3 -m pytest output --junitxml=../report-output.xml -E CB_ASSOCIATE -E LINUX

  only: 
    - schedules
  artifacts:
     when: always
     reports:
       junit: report-*.xml


